server:
  port: 8999

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-PUBLIC
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/, /user/signIn, /token/,  /token/validateToken,
            - Method=POST, PUT


        - id: USER-SERVICE-SECURED
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/, /user/*
            - Method=PUT, DELETE
          filters:
            - name: AuthFilter
            - RewritePath=/user/(?<RID>.*), /user/$\{RID}


        - id: IMAGE-SERVICE
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - name: AuthFilter


