server:
  port: 8999

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-PUBLIC
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/signIn, /user/signUp, /token/validateToken, /token/refreshToken, /token/revokeToken

        - id: USER-SERVICE-SECURED
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/update
          filters:
            - name: AuthFilter

        - id: IMAGE-SERVICE
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - name: AuthFilter


