server:
  port: 9000


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
          - Path=/user/**
        - id: IMAGE-SERVICE
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - AuthFilter

eureka:
  instance:
    # Necessary for Docker as it doesn't have DNS entries
    prefer-ip-address: true
    # Necessary for Docker otherwise you will get 172.0.0.x IP
    ip-address: 172.26.208.1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defeaultZone: http://192.168.0.20:8761/eureka
