server:
  port: 8999

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-PUBLIC
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/signIn, /token/validateToken, /token/refreshToken
        - id: IMAGE-SERVICE
          uri: lb://IMAGE-SERVICE
          predicates:
            - Path=/image/**
          filters:
            - name: AuthFilter
#      discovery:
#        locator:
#          enabled: true

